from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database import Base


class RawPost(Base):
    """Unified raw posts synced from MediaCrawler native tables."""

    __tablename__ = "raw_posts"
    __table_args__ = (
        UniqueConstraint("platform", "external_id", name="ux_raw_posts_platform_external_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    platform: Mapped[str] = mapped_column(String(50), nullable=False)
    external_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_table: Mapped[str] = mapped_column(String(64), default="")
    source_raw_id: Mapped[str] = mapped_column(String(255), default="")
    source_keyword: Mapped[str] = mapped_column(String(255), default="")
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    content: Mapped[str] = mapped_column(Text, default="")
    author: Mapped[str] = mapped_column(String(100), default="")
    publish_time: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    url: Mapped[str] = mapped_column(String(500), default="")
    raw_url: Mapped[str] = mapped_column(String(500), default="")
    like_count: Mapped[int] = mapped_column(Integer, default=0)
    collect_count: Mapped[int] = mapped_column(Integer, default=0)
    comment_count: Mapped[int] = mapped_column(Integer, default=0)
    share_count: Mapped[int] = mapped_column(Integer, default=0)
    tags_json: Mapped[str] = mapped_column(Text, default="")
    images_json: Mapped[str] = mapped_column(Text, default="")
    raw_json: Mapped[str] = mapped_column(Text, default="")
    crawl_time: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="active")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    processed: Mapped["ProcessedPost | None"] = relationship(back_populates="raw_post")
    event_links: Mapped[list["EventPostLink"]] = relationship(back_populates="raw_post")


class ProcessedPost(Base):
    """Cleaned post record used by the public opinion agent."""

    __tablename__ = "processed_posts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    raw_post_id: Mapped[int] = mapped_column(ForeignKey("raw_posts.id"), unique=True)
    platform: Mapped[str] = mapped_column(String(50), nullable=False)
    note_id: Mapped[str] = mapped_column(String(255), default="")
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    content: Mapped[str] = mapped_column(Text, default="")
    source_keyword: Mapped[str] = mapped_column(String(255), default="")
    publish_date: Mapped[str] = mapped_column(String(20), default="")
    publish_time_raw: Mapped[str] = mapped_column(Text, default="")
    author_name: Mapped[str] = mapped_column(String(128), default="")
    tags_json: Mapped[str] = mapped_column(Text, default="")
    note_url: Mapped[str] = mapped_column(String(500), default="")
    raw_note_url: Mapped[str] = mapped_column(String(500), default="")
    images_json: Mapped[str] = mapped_column(Text, default="")
    like_count: Mapped[int] = mapped_column(Integer, default=0)
    collect_count: Mapped[int] = mapped_column(Integer, default=0)
    comment_count: Mapped[int] = mapped_column(Integer, default=0)
    share_count: Mapped[int] = mapped_column(Integer, default=0)
    heat_score: Mapped[float] = mapped_column(Float, default=0.0)
    sentiment: Mapped[str] = mapped_column(String(20), default="neutral")
    sentiment_score: Mapped[float] = mapped_column(Float, default=0.0)
    risk_level: Mapped[str] = mapped_column(String(20), default="low")
    risk_score: Mapped[float] = mapped_column(Float, default=0.0)
    risk_reasons_json: Mapped[str] = mapped_column(Text, default="")
    concerns_json: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Week-1 compatibility fields kept because they already exist in the shared DB.
    author: Mapped[str] = mapped_column(String(100), default="")
    publish_time: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    raw_post: Mapped["RawPost"] = relationship(back_populates="processed")
    event_links: Mapped[list["EventPostLink"]] = relationship(back_populates="processed_post")


class PublicEvent(Base):
    """Public opinion event generated by the opinion agent."""

    __tablename__ = "public_events"
    __table_args__ = (
        UniqueConstraint("event_key", name="ux_public_events_event_key"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_key: Mapped[str | None] = mapped_column(String(255), nullable=True)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    summary: Mapped[str] = mapped_column(Text, default="")
    topic: Mapped[str] = mapped_column(String(100), default="")
    event_type: Mapped[str] = mapped_column(String(64), default="")
    sentiment: Mapped[str] = mapped_column(String(20), default="neutral")
    risk_level: Mapped[str] = mapped_column(String(20), default="low")
    risk_score: Mapped[float] = mapped_column(Float, default=0.0)
    heat_score: Mapped[float] = mapped_column(Float, default=0.0)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    source_count: Mapped[int] = mapped_column(Integer, default=0)
    date_range_json: Mapped[str] = mapped_column(Text, default="")
    source_keywords_json: Mapped[str] = mapped_column(Text, default="")
    top_tags_json: Mapped[str] = mapped_column(Text, default="")
    concerns_json: Mapped[str] = mapped_column(Text, default="")
    risk_reasons_json: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String(20), default="draft")
    reviewed_by: Mapped[str] = mapped_column(String(64), default="")
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    review_comment: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Week-1 single-source field kept for compatibility; new code should prefer EventPostLink.
    source_post_id: Mapped[int | None] = mapped_column(
        ForeignKey("processed_posts.id"), nullable=True
    )

    post_links: Mapped[list["EventPostLink"]] = relationship(back_populates="event")


class EventPostLink(Base):
    """Many-to-many support relation between an event and its source posts."""

    __tablename__ = "event_post_links"
    __table_args__ = (
        Index("idx_event_post_links_event_id", "event_id"),
        Index("idx_event_post_links_processed_post_id", "processed_post_id"),
        Index("idx_event_post_links_raw_post_id", "raw_post_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_id: Mapped[int] = mapped_column(ForeignKey("public_events.id"), nullable=False)
    processed_post_id: Mapped[int | None] = mapped_column(
        ForeignKey("processed_posts.id"), nullable=True
    )
    raw_post_id: Mapped[int | None] = mapped_column(ForeignKey("raw_posts.id"), nullable=True)
    rank: Mapped[int] = mapped_column(Integer, default=0)
    role: Mapped[str] = mapped_column(String(32), default="source")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    event: Mapped["PublicEvent"] = relationship(back_populates="post_links")
    processed_post: Mapped["ProcessedPost | None"] = relationship(back_populates="event_links")
    raw_post: Mapped["RawPost | None"] = relationship(back_populates="event_links")


class UserTask(Base):
    """Retained week-1 personal task table; not part of the week-2 core path."""

    __tablename__ = "user_tasks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String(50), default="default")
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String(20), default="pending")
    due_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class UserSchedule(Base):
    """Retained week-1 schedule table; not part of the week-2 core path."""

    __tablename__ = "user_schedules"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String(50), default="default")
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    start_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    end_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    location: Mapped[str] = mapped_column(String(200), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
